### PR TITLE
Migrate to espree 2.x

### LINKED ISSUE #349: Upgrade to latest espree
Is it possible to upgrade the espree to latest version, which supports 'ObjectRestSpread'

### PR DESCRIPTION
**Pull request by wbinnssmith**
Resolves #349.

Begin depending on espree 2.x, and migrate:

* `ParameterDefault` node type to estree's `AssignmentPattern` type
* Fix an invalid use of arrow functions in a test which began throwing in espree 2.x

... and depend on [rocambole #28](https://github.com/millermedeiros/rocambole/pull/28) to account for espree 2.x's removal of `TryStatement`'s handler list, and use only one handler instead.

### CODE REVIEW

**Comment by wbinnssmith** [comment]
Note that this depends on millermedeiros/rocambole#28 being merged, so the build is currently failing.

**Comment by wbinnssmith** [comment]
Just pushed a commit to switch rocambole to my fork (so travis passes), but I'll change it back if/when that gets published to npm.

**Comment by millermedeiros** [comment]
rocambole@0.7.0 was just published.

I'm going to start fixing all the pending [esformatter v0.8.0 bugs](https://github.com/millermedeiros/esformatter/milestones/v0.8.0) next week and plan to do a release by the end of the week.

thanks for all the contributions!

**Comment by wbinnssmith** [comment]
any time! I love esformatter so thank *you* :smile:

I just redirected the dependency on rocambole@0.7 and squashed things down.

**Comment by millermedeiros** [comment]
thanks a lot!

**Pull request merged**
