### PR TITLE
Add whitespace preset for ImportSpecifier braces

### PR DESCRIPTION
**Pull request by kewah**
Hej,

I've added the possibility to define the number of whitespace in between `import`'s braces:
`import {x} from 'foo'`.

I've used `ImportSpecifierOpeningBrace` and `ImportSpecifierClosingBrace`, let me know if it should be another name since it is also used for [ExportSecifier](lib/hooks/ExportSpecifier.js).

Thanks

### CODE REVIEW

**Comment by millermedeiros** [comment]
the estree project uses [`ModuleSpecifier`](https://github.com/estree/estree/blob/master/es6.md#modulespecifier) as the base type for `ImportSpecifier`, `ExportSpecifier`, `ImportDefaultSpecifier` and `ImportNamespaceSpecifier`... maybe we should use `ModuleSpecifierOpeningBrace` instead?

**Comment by kewah** [comment]
Sounds even better :+1: 
Commit amended.

**Comment by millermedeiros** [comment]
@kewah thanks a lot for the pull request!

**Comment by maitriyogin** [comment]
Hiya,
I'm having a nightmare trying to get rid of the space in the opening and closing of my imports `import { something }` should be `import {something}` ...
Whats the config needed to achieve this?
Cheers,
Stephen.

**Comment by kewah** [comment]
@maitriyogin Which version do you use? 

Here is the config I use to achieve that
```
  "whiteSpace": {
    "before": {
      "ModuleSpecifierClosingBrace": 0,
    },
    "after": {
      "ModuleSpecifierOpeningBrace": 0
    }
  }
```

**Pull request merged**
