### PR TITLE
IfStatement: Multi-line test with comments

### PR DESCRIPTION
**Pull request by jzaefferer**
This adds a failing test for IfStatement, when the test is split over multiple lines and includes LineComments.

### CODE REVIEW

**Comment by jzaefferer** [comment]
I've looked into `lib/hooks/IfStatement` and its `getIndentEdges` method. I don't see anything wrong with this that would explain this failure:

```js
// test (IfStatementConditional)
edges.push({
  level: opts.IfStatementConditional,
  startToken: _tk.findPrevNonEmpty(test.startToken),
  endToken: test.endToken,
});
```
That looks like it should include comment tokens...

**Comment by millermedeiros** [comment]
Comment is not "empty".. Should probably get the previous `)` instead

**Comment by jzaefferer** [comment]
> Should probably get the previous `)` instead

Doesn't the IfStatementConditional start with a `(`? How does looking for `(` help?

**Comment by jzaefferer** [comment]
Updated with a fix, tests are passing. I figured that looking for previous opening parens is fragile, so instead I went from the `node.startToken` to the next opening paren. That should be pretty reliable.

**Comment by jzaefferer** [comment]
Kinda related to 07a6efd2f2bfa5b8b9ea70335c5b94417fb50493

**Comment by millermedeiros** [comment]
> looking for previous opening parens is fragile, so instead I went from the node.startToken to the next opening paren. That should be pretty reliable.

yes, there are many places where I overlooked the token search logic (specially the first hooks that I implemented) - forgot that parenthesis sometimes are not the `node.startToken` even if they are surrounded by parenthesis, and also that comments are not *empty*...

**Pull request merged**
