### PR TITLE
Some ES6 fixes around Export and Object destructuration

### PR DESCRIPTION
**Pull request by RaitoBezarius**
As asked by @millermedeiros in #316 issue, here is my pull request fixing some ES6 issues that I've encountered on my codebase when formatting it. (mainly `export` statements and object destructuration: `ObjectPattern`).

I think that I've cleaned all debugging statements, but anyway if there is something wrong, I'll gladly adapt my pull request !

Thanks !

### CODE REVIEW

**Comment by millermedeiros** [comment]
can you rebase and squash all the commits?

**Comment by RaitoBezarius** [comment]
Sure !

**Comment by RaitoBezarius** [comment]
Done !

**Comment by millermedeiros** [comment]
rebased; fixed some errors & removed unused vars and landed on master: https://github.com/millermedeiros/esformatter/commit/93aab2d98c7531e0d9e5a19d5d878d4f708eaeec

thanks for your contribution!

**Pull request closed without merging**
