### PR TITLE
Update jquery preset to tolerate single line objects

### PR DESCRIPTION
**Pull request by jzaefferer**
This disables a big chunk of useful formatting, but until I can figure out a better solution, this is preferable over messing up existing acceptable code.

### CODE REVIEW

**Comment by leobalter** [comment]
typo on commit and PR's title. s/Upate/Update

**Comment by jzaefferer** [comment]
Thanks, updated. Broken keyboard is annoying.

**Comment by millermedeiros** [comment]
this looks like a good change to me until we have a plugin that does the smart logic.

**Comment by jzaefferer** [comment]
Closed by 59e4681ec854af4debb5d170a2e7e0ff452fb58a (missed updating the commit message after rebase).

**Pull request closed without merging**
